### ISSUE TITLE
failed test: AmberParmBuilder.Test.test_capIrregular  

### ISSUE THREAD

**Issue by graik** [graik/biskit#3]
Tested on: Linux64 (Ubuntu 14.04), with AmberTools 15

ERROR: AmberParmBuilder.Test.test_capIrregular  
Traceback (most recent call last):
  File "/home/raik/data/py/Biskit/AmberParmBuilder.py", line 680, in test_capIrregular
    self.m4 = self.a.capACE( normal, 0 )
  File "/home/raik/data/py/Biskit/AmberParmBuilder.py", line 313, in capACE
    return cleaner.capACE( model, chain, breaks=True )
  File "/home/raik/data/py/Biskit/PDBCleaner.py", line 390, in capACE
    if len(c_start) != r.lenChains( breaks=breaks ):
  File "/home/raik/data/py/Biskit/PDBModel.py", line 2518, in lenChains
    singleRes=singleRes, solvent=solvent))
  File "/home/raik/data/py/Biskit/PDBModel.py", line 2796, in chainIndex
    solvent=solvent, force=force )
  File "/home/raik/data/py/Biskit/PDBModel.py", line 2880, in chainBreaks
    bb   = self.take( i_bb )
  File "/home/raik/data/py/Biskit/PDBModel.py", line 2206, in take
    r.residues = self.residues.take( i_res, r )
  File "/home/raik/data/py/Biskit/ProfileCollection.py", line 876, in take
    raise ProfileError( "Can't take sub-profile %r: %r" % (key,why) )
ProfileError: Can't take sub-profile 'biomol': IndexError('index 2 is out of bounds for size 2',)

**Comment by graik** [comment]
fixed by multiple changes in ProfileCollection concat.
