### ISSUE TITLE
failed test(s): DSSP wrapper

### ISSUE THREAD

**Issue by graik** [graik/biskit#5]
Tested on Ubuntu 14.04 with DSSP 2.0.4

ERROR: DSSP.Test.test_DSSP  

Traceback (most recent call last):
  File "/home/raik/data/py/Biskit/DSSP.py", line 272, in test_DSSP
    self.result = self.dssp.run()
  File "/home/raik/data/py/Biskit/Executor.py", line 557, in run
    self.finish()
  File "/home/raik/data/py/Biskit/DSSP.py", line 240, in finish
    self.result = self.parse_result( )
  File "/home/raik/data/py/Biskit/DSSP.py", line 134, in parse_result
    'Dssp result file %s empty'%self.f_out
Dssp_Error: Dssp result file /tmp/dsspcmbi_LaCQ7V.out empty

This also raises another test error in PDBDope: PDBDope.Test.test_addSecondaryStructure

**Comment by graik** [comment]
fixed.
